Improve associated no reflection error
Based on fbbbfa8 so thanks to @ykpythemind

before:

```
Post.where.associated(:cars).to_a # Post does not have association named `cars`

=> NoMethodError: undefined method `table_name' for nil:NilClass
```

after:

```
Post.where.associated(:cars).to_a
=> ArgumentError: An association named `:cars` does not exist on the model `Post`.
```